name = "LocalSignalAttributes"
uuid = "0a92bf9b-4da3-44e8-9286-830175b27cf8"
authors = ["Akshika Rohatgi, Sergey Fomel"]
version = "1.0.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6.7"
FFTW = "1.5.0"
LinearAlgebra = "1.9.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
